import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Button from '../components/Button'
import PostSmall from '../components/PostSmall'
import { prisma } from '../server/db/client'


import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ posts }) {

  const router = useRouter();

  //post: {id, title, code, language, totalLikes, totalComments, creratedAt}
  // const post = [];                                      
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <Button onClick={() => router.push('/addPost')}>
            Post A New Movie
          </Button>

          <ul>
            {posts?.map(post => (
              <li key={post.id}>
                  <PostSmall
                   post={post}
                   href={`/code/${post.id}`}
                   onLike={() => console.log("like post", post.id)}
                   onComment={() => console.log("comment post", post.id)}
                   onShare={() => console.log("share post", post.id)}
                   >
                  </PostSmall>
              </li>
            ))}
          </ul>

        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  // will always run on the server
  //newest first
  const posts = await prisma.post.findMany({
    orderBy: {
      createdAt: 'desc',
    },
  })

  return {
    props: {
      posts: JSON.parse(JSON.stringify(posts)),
    },
  }
}
