import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Button from '../components/Button'
import PostSmall from '../components/PostSmall'
import { prisma } from '../server/db/client'
import handler from './api/posts/deletePost'
// import SiteNavigation from '@/components/SiteNavigation'


import { useRouter } from 'next/router'

export async function deletePostSmallById(id) {
  const deletedPost = await prisma.post.delete({
    where: { id: Number(id) },
  })
  console.log(deletedPost)
 }


export default function Home({ posts }) {

  const router = useRouter();

  //post: {id, title, code, language, totalLikes, totalComments, creratedAt}
  // const post = [];      
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>

          <Button onClick={() => router.push('/addPost')}>
            Post A New Movie
          </Button>

          <div style={{width:'600px', height:'fit-content'}}>
            {posts?.map(post => (
              <div key={post.id}>
                  <PostSmall
                   post={post}
                   href={`/code/${post.id}`}
                   onLike={() => console.log("like post", post.id)}
                   onComment={() => console.log("comment post", post.id)}
                   onShare={() => console.log("share post", post.id)}
                   onDelete={() => deletePostSmallById(post.id)}
                  // onDelete={() => handler(post.id)}
                   >
                  </PostSmall>
              </div>
            ))}
          </div>

        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  // will always run on the server
  //newest first
  const posts = await prisma.post.findMany({
    orderBy: {
      createdAt: 'desc',
    },
  })

  return {
    props: {
      posts: JSON.parse(JSON.stringify(posts)),
    },
  }
}
